spring:
  application:
    name: comment-analyzer

  ai:
    model:
      chat: ollama

    ollama:
      base-url: http://localhost:11434

      chat:
        model: qwen2.5:1.5b
        options:
          temperature: 0